CREATE TABLE documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_path VARCHAR2(255),
    file_name VARCHAR2(255),
    version NUMBER,
    download_status VARCHAR2(50),
    error_message CLOB,
    timestamp TIMESTAMP,
    migration_tracker_id NUMBER,
    versionId VARCHAR(50)
);

ALTER TABLE documents ADD migration_tracker_id NUMBER;

CREATE TABLE migration_tracker (
     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    csv_file_name VARCHAR(255),
    from_date TIMESTAMP,
    to_date TIMESTAMP,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status VARCHAR(50)
);

ALTER TABLE documents ADD CONSTRAINT fk_migration_tracker
FOREIGN KEY (migration_tracker_id)
REFERENCES migration_tracker(id);

ALTER TABLE documents
ADD versionId VARCHAR2(50) NOT NULL;


SELECT 
    SUM(EXTRACT(SECOND FROM (end_time - start_time)) +
        60 * EXTRACT(MINUTE FROM (end_time - start_time)) +
        3600 * EXTRACT(HOUR FROM (end_time - start_time)) +
        86400 * (TRUNC(end_time) - TRUNC(start_time))) / 3600 AS total_hours
FROM documents
WHERE end_time IS NOT NULL AND start_time IS NOT NULL;


