CREATE TABLE documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_path VARCHAR2(255),
    file_name VARCHAR2(255),
    version NUMBER,
    download_status VARCHAR2(50),
    error_message CLOB,
    timestamp TIMESTAMP
);

ALTER TABLE documents ADD migration_tracker_id NUMBER;

CREATE TABLE migration_tracker (
     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    csv_file_name VARCHAR(255),
    from_date TIMESTAMP,
    to_date TIMESTAMP,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status VARCHAR(50)
);

ALTER TABLE documents ADD CONSTRAINT fk_migration_tracker
FOREIGN KEY (migration_tracker_id)
REFERENCES migration_tracker(id);


SELECT
    FLOOR(SUM((end_time - start_time) * 24)) AS total_hours,
    FLOOR(SUM((end_time - start_time) * 24 * 60)) - FLOOR(SUM((end_time - start_time) * 24)) * 60 AS total_minutes,
    MOD(FLOOR(SUM((end_time - start_time) * 24 * 60 * 60)), 60) AS total_seconds
FROM documents
WHERE end_time IS NOT NULL AND start_time IS NOT NULL;

